{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Response Body and Req Body",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\", type=\"http\"}\r\n| regexp `\"req\":(?P<req_raw>\\{.*\\}|\\[\\])`\r\n| regexp `\"res\":(?P<res_raw>(\\[[\\s\\S]*\\]|\\{.*\\}))`\r\n| label_format req=\"{{ .req_raw }}\"\r\n| label_format res=\"{{ .res_raw }}\"\r\n"
    }
   ]
  },
  {
   "title": "New Panel",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "endpoint_latency_ms_milliseconds{source=\"jwt-pizza-service\"}",
     "legendFormat": "Endpoint Latency"
    },
    {
     "expr": "pizza_creation_latency_ms_milliseconds{source=\"jwt-pizza-service\"}",
     "legendFormat": "Pizza Creation Latency"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(pizza_revenue_total{source=\"jwt-pizza-service\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "rate(pizza_sold_total{source=\"jwt-pizza-service\"}[3m])",
     "legendFormat": "pizza purchase"
    },
    {
     "expr": "increase(pizza_creation_failures_total{source=\"jwt-pizza-service\"}[3m])",
     "legendFormat": "pizza fail"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_usage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "cpu_usage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Authentication per min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "rate(auth_attempts_total{status=\"success\", source=\"jwt-pizza-service\"}[3m])",
     "legendFormat": "auth success"
    },
    {
     "expr": "rate(auth_attempts_total{status=\"failure\", source=\"jwt-pizza-service\"}[3m])",
     "legendFormat": "auth fail"
    }
   ]
  },
  {
   "title": "HTTP Req Method per Min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "rate(http_requests_total{source=\"jwt-pizza-service\"}[3m])\r\n",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}