{
 "title": "Pizza Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "endpoint_latency_ms_milliseconds{source=\"jwt-pizza-service\"}",
     "legendFormat": "Endpoint Latency"
    },
    {
     "expr": "pizza_creation_latency_ms_milliseconds{source=\"jwt-pizza-service\"}",
     "legendFormat": "Pizza Creation Latency"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pizza_revenue_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(pizza_sold_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "pizza purchase"
    },
    {
     "expr": "increase(pizza_creation_failures_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "pizza fail"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_usage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "cpu_usage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Authentication per min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(auth_attempts_total{status=\"success\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "auth success"
    },
    {
     "expr": "rate(auth_attempts_total{status=\"failure\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "auth fail"
    }
   ]
  },
  {
   "title": "HTTP Req Method per Min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(http_requests_total{source=\"jwt-pizza-service\"}[1m])\r\n",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}